version: "3.7"

services:
  app:
    image: node:lts
    command: sh -c "npm install && node ."
    working_dir: /hey
    volumes:
      - ./:/backend
      - wordledat-db:/data

volumes:
  wordledat-db:
